version: '3'

services:
    nginx:
        build:
            context: $PWD/docker/context/nginx
            dockerfile: $PWD/docker/build/nginx
        restart: always
        hostname: yunnet_nginx
        tty: true
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../:/home/unt
            - /var/log/nginx
            - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php
        command: bash /home/unt/unt_2/scripts/nginx.sh
        networks:
            - unt_1_database
    # PHP 7.4
    php:
        build:
            context: $PWD/docker/context/php
            dockerfile: $PWD/docker/build/php
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../:/home/unt
            # связь с внутренними файлами
            - $PWD/config/php/php$UNT_PRODUCTION.ini:/usr/local/etc/php/php.ini
            - $PWD/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - $PWD/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - memcached
            - text_engine
            - mail
        hostname: yunnet_php
        tty: true
        networks:
            - unt_1_database

    memcached:
        build:
            context: $PWD/docker/context/memcached
            dockerfile: $PWD/docker/build/memcached
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../:/home/unt
        networks:
            - unt_1_database
        restart: unless-stopped
        hostname: yunnet_memcached
        tty: true

    mail:
        build:
            dockerfile: $PWD/docker/build/postfix
            context: $PWD/docker/context/postfix
        volumes:
            - $PWD/../:/home/unt
            - $PWD/config/postfix/exim4.conf.template:/etc/exim4/exim4.conf.template
            - $PWD/config/postfix:/etc/postfix
            - $PWD/config/postfix/mail-addresses:/etc/mail-addresses
        env_file:
            - $PWD/configs.env
        restart: unless-stopped
        hostname: yunnet_mailer
        networks:
            - unt_1_database
        tty: true
        ports:
            - "25:25"

    text_engine:
        build:
            context: $PWD/docker/context/text_engine
            dockerfile: $PWD/docker/build/text_engine
        volumes:
            - $PWD/../:/home/unt
        restart: unless-stopped
        hostname: yunnet_text_engine
        tty: true
        env_file:
            - $PWD/configs.env
        links:
            - memcached
        networks:
            - unt_1_database

    poll_engine:
        restart: unless-stopped
        hostname: yunnet_poll_engine
        tty: true
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../:/home/unt
        links:
            - memcached
        ports:
            - "8080:80"
        build:
            context: $PWD/docker/context/poll_engine
            dockerfile: $PWD/docker/build/poll_engine
        networks:
            - unt_1_database

networks:
    unt_1_database:
        external: true