version: '3'

services:
    nginx:
        build:
            context: $PWD/docker/context/nginx
            dockerfile: $PWD/docker/nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../../:/home/unt
            - /var/log/nginx
            - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php
        command: bash /home/unt/config/local/scripts/nginx.sh
    php:
        build:
            context: $PWD/docker/context/php
            dockerfile: $PWD/docker/php
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../../:/home/unt
            - $PWD/config/php/php$UNT_PRODUCTION.ini:/usr/local/etc/php/php.ini
            - $PWD/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - $PWD/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - memcached
            - text_engine
    memcached:
        image: memcached:latest
        container_name: memcached
    mail:
        build:
            context: $PWD/docker/context/postfix
            dockerfile: $PWD/docker/postfix
        volumes:
            - $PWD/../../:/home/unt
            - $PWD/config/postfix:/config
            - $PWD/config/postfix/mailname:/etc/mailname
        env_file:
            - $PWD/configs.env
    text_engine:
        env_file:
            - $PWD/configs.env
        build:
            context: $PWD/docker/context/text_engine
            dockerfile: $PWD/docker/text_engine
        volumes:
            - $PWD/../../:/home/unt
        links:
            - memcached
    poll_engine:
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../../:/home/unt
        links:
            - memcached
        ports:
            - "8080:80"
        build:
            context: $PWD/docker/context/poll_engine
            dockerfile: $PWD/docker/poll_engine
