version: '3'

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/unt:/home/unt
            - /var/log/nginx
            - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/config/nginx/yunnet.conf:/etc/nginx/yunnet.conf
        links:
            - php
    php:
        build:
            context: $PWD/docker/context/php
            dockerfile: $PWD/docker/php
        volumes:
            - /home/unt:/home/unt
            - $PWD/config/php/php.ini:/usr/local/etc/php/php.ini
            - $PWD/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - $PWD/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - memcached
    memcached:
        image: memcached:latest
        container_name: memcached
        ports:
            - "11211:11211"
