name: lint

# push all commits to all branches
on:
  push

# lint uses only test server
env:
  UNT_PRODUCTION: 0

jobs:
  lint:
    name: Project lint
    runs-on: self-hosted
    steps:
      - name: Init project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Lint files
        run: |
          for file in $(git diff --name-only --diff-filter=ACMR HEAD~1 | grep -E "(.php$|.html$)"); do php -l $file; done\
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: lint
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.PRIVATE_KEY }}